# Generated by Django 3.2.15 on 2022-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citingpaper",
            name="comparisondate",
            field=models.DateField(
                blank=True,
                help_text="Best available date field",
                null=True,
                verbose_name="Comparison date",
            ),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="comparisondate",
            field=models.DateField(
                blank=True,
                help_text="Best available date field",
                null=True,
                verbose_name="Comparison date",
            ),
        ),
        migrations.AddField(
            model_name="retractionnotice",
            name="comparisondate",
            field=models.DateField(
                blank=True,
                help_text="Best available date field",
                null=True,
                verbose_name="Comparison date",
            ),
        ),
    ]
