# Generated by Django 3.2.15 on 2022-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0002_comparison_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="papers",
            new_name="citing_papers",
        ),
        migrations.AddField(
            model_name="author",
            name="retracted_papers",
            field=models.ManyToManyField(
                related_name="authors", to="retractions.RetractedPaper"
            ),
        ),
    ]
