# Generated by Django 3.2.15 on 2022-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0006_remove_retractionnotice_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="pairs",
            field=models.ManyToManyField(
                related_name="contactable_authors",
                to="retractions.CitationRetractionPair",
            ),
        ),
    ]
