# Generated by Django 3.2.15 on 2022-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0008_mail_sent_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="retractedpaper",
            name="stratifying_group",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
