# Generated by Django 3.2.15 on 2022-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0009_retractedpaper_stratifying_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retractedpaper",
            name="in_rct_cohort",
        ),
        migrations.AddField(
            model_name="citingpaper",
            name="cited_in_rct",
            field=models.BooleanField(default=False),
        ),
    ]
