# Generated by Django 3.2.15 on 2023-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retractions", "0010_cited_in_rct"),
    ]

    operations = [
        migrations.AddField(
            model_name="citingpaper",
            name="errors",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="retractedpaper",
            name="errors",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="retractionnotice",
            name="errors",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
